<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magento.com for more information.
 *
 * @category    Mage
 * @package     Mage
 * @copyright  Copyright (c) 2006-2017 X.commerce, Inc. and affiliates (http://www.magento.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if (version_compare(phpversion(), '5.3.0', '<')===true) {
    echo  '<div style="font:12px/1.35em arial, helvetica, sans-serif;">
<div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
<h3 style="margin:0; font-size:1.7em; font-weight:normal; text-transform:none; text-align:left; color:#2f2f2f;">
Whoops, it looks like you have an invalid PHP version.</h3></div><p>Magento supports PHP 5.3.0 or newer.
<a href="http://www.magentocommerce.com/install" target="">Find out</a> how to install</a>
 Magento using PHP-CGI as a work-around.</p></div>';
    exit;
}

/**
 * Compilation includes configuration file
 */
define('MAGENTO_ROOT', getcwd());

$compilerConfig = MAGENTO_ROOT . '/includes/config.php';
if (file_exists($compilerConfig)) {
    include $compilerConfig;
}

$mageFilename = MAGENTO_ROOT . '/app/Mage.php';
$maintenanceFile = 'maintenance.flag';

if (!file_exists($mageFilename)) {
    if (is_dir('downloader')) {
        header("Location: downloader");
    } else {
        echo $mageFilename." was not found";
    }
    exit;
}

if (file_exists($maintenanceFile)) {
    include_once dirname(__FILE__) . '/errors/503.php';
    exit;
}

require MAGENTO_ROOT . '/app/bootstrap.php';
require_once $mageFilename;

//Varien_Profiler::enable();

if (isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) {
    Mage::setIsDeveloperMode(true);
}

// ini_set('display_errors', 1);
//Mage::setIsDeveloperMode(true);

umask(0);

// // generate coupon
// function grabCode() {
//   // Get the rule in question
//   $rule = Mage::getModel('salesrule/rule')->load(92); //ID of coupon in question

//   // Define a coupon code generator model instance
//   // Look at Mage_SalesRule_Model_Coupon_Massgenerator for options
//   $generator = Mage::getModel('salesrule/coupon_massgenerator');

//   $parameters = array(
//       'count'=>5,
//       'format'=>'alphanumeric',
//       'dash_every_x_characters'=>4,
//       'prefix'=>'ABCD-EFGH-',
//       'suffix'=>'-WXYZ',
//       'length'=>8
//   );

//   if( !empty($parameters['format']) ){
//     switch( strtolower($parameters['format']) ){
//       case 'alphanumeric':
//       case 'alphanum':
//         $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC );
//         break;
//       case 'alphabetical':
//       case 'alpha':
//         $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHABETICAL );
//         break;
//       case 'numeric':
//       case 'num':
//         $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_NUMERIC );
//         break;
//     }
//   }

//   $generator->setDash( !empty($parameters['dash_every_x_characters'])? (int) $parameters['dash_every_x_characters'] : 0);
//   $generator->setLength( !empty($parameters['length'])? (int) $parameters['length'] : 6);
//   $generator->setPrefix( !empty($parameters['prefix'])? $parameters['prefix'] : '');
//   $generator->setSuffix( !empty($parameters['suffix'])? $parameters['suffix'] : '');

//   // Set the generator, and coupon type so it's able to generate
//   $rule->setCouponCodeGenerator($generator);
//   $rule->setCouponType( Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO );

//   $coupon = $rule->acquireCoupon();
//   $coupon->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)->save();
//   $code = $coupon->getCode();
//   return $code;
// };
// // form handler
// if ($_REQUEST['free_sample'] == '1') {
//   echo grabCode();
//   exit;
// }




/* Store or website code */
$mageRunCode = isset($_SERVER['MAGE_RUN_CODE']) ? $_SERVER['MAGE_RUN_CODE'] : '';

/* Run store or run website */
$mageRunType = isset($_SERVER['MAGE_RUN_TYPE']) ? $_SERVER['MAGE_RUN_TYPE'] : 'store';

Mage::run($mageRunCode, $mageRunType);