<?php
define('MAGENTO_ROOT', getcwd());

$compilerConfig = MAGENTO_ROOT . '/includes/config.php';
if (file_exists($compilerConfig)) {
    include $compilerConfig;
}

$mageFilename = MAGENTO_ROOT . '/app/Mage.php';
require MAGENTO_ROOT . '/app/bootstrap.php';
require_once $mageFilename;

umask();

Mage::run('base', 'store');

function grabCode() {
  // Get the rule in question
  $rule = Mage::getModel('salesrule/rule')->load(92); //ID of coupon in question

  // Define a coupon code generator model instance
  // Look at Mage_SalesRule_Model_Coupon_Massgenerator for options
  $generator = Mage::getModel('salesrule/coupon_massgenerator');

  $parameters = array(
      'count'=>5,
      'format'=>'alphanumeric',
      'dash_every_x_characters'=>4,
      'prefix'=>'ABCD-EFGH-',
      'suffix'=>'-WXYZ',
      'length'=>8
  );

  if( !empty($parameters['format']) ){
    switch( strtolower($parameters['format']) ){
      case 'alphanumeric':
      case 'alphanum':
        $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC );
        break;
      case 'alphabetical':
      case 'alpha':
        $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHABETICAL );
        break;
      case 'numeric':
      case 'num':
        $generator->setFormat( Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_NUMERIC );
        break;
    }
  }

  $generator->setDash( !empty($parameters['dash_every_x_characters'])? (int) $parameters['dash_every_x_characters'] : 0);
  $generator->setLength( !empty($parameters['length'])? (int) $parameters['length'] : 6);
  $generator->setPrefix( !empty($parameters['prefix'])? $parameters['prefix'] : '');
  $generator->setSuffix( !empty($parameters['suffix'])? $parameters['suffix'] : '');

  // Set the generator, and coupon type so it's able to generate
  $rule->setCouponCodeGenerator($generator);
  $rule->setCouponType( Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO );

  $coupon = $rule->acquireCoupon();
  $coupon->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)->save();
  $code = $coupon->getCode();
  return $code;
};
$to = 'tatan42@gmail.com';
$subject = 'dat sweet code';
// $message = grabCode();
$headers = 'From:' . 'who@knows.notme';
// mail($to, $subject, $message, $headers);

$message = Mage::getBaseUrl();
echo $message;
 
?>